### ISSUE TITLE
Improve the speed of gocleasy using godu as reference

### ISSUE THREAD

**Issue by gedw99** [aams-eam/gocleasy#1]
its nice 

i use this github.com/viktomas/godu as its much faster at searching for the files.

might be useful for gocleasy...

**Comment by aams-eam** [comment]
Hi @gedw99,

It looks awesome. I will definitely have a look!

**Comment by aams-eam** [comment]
Hello @gedw99,

I have taken into consideration the repository you mentioned. Gocleasy is now faster and more RAM efficient.
You can have a look here [Gocleasy v2.0.0](https://github.com/aams-eam/gocleasy/releases/tag/2.0.0).
The only drawback, as with godu, is that for systems with a large number of folders, the program may crash due to high RAM consumption.

Thank you very much for your input!

**Comment by gedw99** [comment]
Nice work @aams-eam 

it’s a really outstanding and useful app..

**Comment by aams-eam** [comment]
Thanks @gedw99!
